# -*- coding: utf-8 -*-
REFERENCE_TICKERS = {
    "XU100": "XU100.IS",
    "XU030": "XU030.IS",
    "XBANK": "XBANK.IS",
    "XUTUM": "XUTUM.IS",
    "XBANA": "XBANA.IS",
}

FALLBACK_SYMBOLS = [
    "ASELS","THYAO","EREGL","TUPRS","GARAN","AKBNK","ISCTR","YKBNK",
    "KCHOL","SAHOL","BIMAS","FROTO","TOASO","TCELL","SISE","PETKM",
    "SASA","PGSUS","MGROS","ASTOR","HEKTS","KRDMD","ENKAI","EKGYO",
    "GUBRF","OYAKC","TTKOM","ALARK","ZOREN","ODAS"
]
